# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
	# Use the ubuntu trusty tahr box
	config.vm.box = "ubuntu/trusty64"

	# Run the provisioning scriopt
	config.vm.provision :shell, path: "bootstrap.sh"

	# Forward the host port 8080 to port 80 on this guest machine
	config.vm.network "forwarded_port", guest: 80, host: 8080
end
